print("-->Hi my name is Alice and im going to ask you some questions if you dont mind")
name = input("--> What is your name? ")
print(f"Hello {name} and welcome to CT8")
print ("")
print ("")
Food = input ("pick a food any food ")
print("")
print("")
Illness = input ("now name any Illness ")
print("")
print("")
City = input("one last question name a city ")
print("")
print("")
print("-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-")
print(f"A random day {name} started to eat some {Food}, but then started to feel ill so {name} went to the doctors office and was diagnosed with {Illness}. After hearing this news {name} traveled to {City}, which made {name} feel much better better.")
print(f"Thank you so much {name} I hope you have a great rest of your day.")
print("-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-")